swagger: "2.0"
info:
  version: "1.0.0"
  title: 'CQUBE'

basePath: "/v0"

tags:
  - name: "spec"
  - name: "ingestion"

schemes:
  - "https"
  - "http"

paths:
  /spec/event:
    post:
      tags:
        - "spec"
      summary: "Create a new event Specification"
      description: "Add new event Specification"
      operationId: "eventSpecification"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            example:
              program: student-attendance
              input:
                type: object
                properties:
                  date:
                    type: string
                    shouldNotNull: true
                    format: date
                  school_id:
                    type: string
                    shouldNotNull: true
                  grade_id:
                    type: string
                    shouldNotNull: true
                  district_id:
                    type: string
                    shouldNotNull: true
                  block_id:
                    type: string
                    shouldNotNull: true
                  cluster_id:
                    type: string
                    shouldNotNull: true
                  schoolcategory_id:
                    type: string
                    shouldNotNull: true
                  gender:
                    type: string
                    shouldNotNull: true
                  students_attendance_marked:
                    type: string
                    shouldNotNull: true
                  students_marked_present:
                    type: string
                    shouldNotNull: true
                  total_students:
                    type: string
                    shouldNotNull: true
                  teachers_marked:
                    type: string
                    shouldNotNull: true
                  teachers_marked_present:
                    type: string
                    shouldNotNull: true
                  total_teachers:
                    type: string
                    shouldNotNull: true

      responses:
        200:
          description: "Event Spec Created Successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Event Spec Created Successfully"
              event_name:
                type: "string"
                example: "students_attendance"
        400:
          description: "Something went wrong"
          schema:
            $ref: "#/definitions/generic_error"
  
  /spec/dimension:
    post:
      tags:
        - "spec"
      summary: "Create a new dimension Specification"
      description: "Add new dimension Specification"
      operationId: "dimensionSpecification"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            example:
              program: school
              input:
                type: object
                properties:
                  school_id:
                    type: string
                    shouldNotNull: true
                  udise_code:
                    type: string
                    shouldNotNull: true
                  school_name:
                    type: string
                    shouldNotNull: true
                  schoolcategory_id:
                    type: string
                    shouldNotNull: true
                  block_id:
                    type: string
                    shouldNotNull: true
                  cluster_id:
                    type: string
                    shouldNotNull: true
                  cluster_name:
                    type: string
                    shouldNotNull: true
                  block_name:
                    type: string
                    shouldNotNull: true
                  district_id:
                    type: string
                    shouldNotNull: true
                  district_name:
                    type: string
                    shouldNotNull: true
                  latitude:
                    type: number
                    shouldNotNull: false
                  longitude:
                    type: number
                    shouldNotNull: false

      responses:
        200:
          description: "Dimension Spec Created Successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Dimension Spec Created Successfully"
              dimension_name:
                type: "string"
                example: "school"
        400:
          description: "Something went wrong"
          schema:
            $ref: "#/definitions/generic_error"
  
  /spec/schedule:
    post:
      tags:
        - "spec"
      summary: "Update a Schedule"
      description: "Update a schedule"
      operationId: "updateSchedule"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              processor_group_name:
                type: "string"
                example: "Plugin Student Attendance aws"
              scheduled_at:
                type: "string"
                example: "0 0/1 * 1/1 * ? *"
      responses:
        200:
          description: "Successfully updated the schedule"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Successfully updated the schedule"
        400:
          description: "Something went wrong"
          schema:
            $ref: "#/definitions/generic_error"

definitions:
  generic_error:
      type: "object"
      properties:
        message:
          type: "string"
          example: "Invalid Input"